import { useEffect, useState, type FormEvent } from 'react'
import { addExamQuestion, createExam, getExamResults, getManagedExams } from '../api/examApi'
import type { CodeLanguage, ExamQuestionType, ExamSummary, TeacherExamResult } from '../types/exam'

export function TeacherExamStudio({ onBack }: { onBack: () => void }) {
  const [exams,setExams]=useState<ExamSummary[]>([]); const [examId,setExamId]=useState(''); const [mode,setMode]=useState<'create'|'question'|'results'>('create');
  const [values,setValues]=useState<Record<string,string>>({duration:'60',points:'1',position:'1',type:'MULTIPLE_CHOICE',language:'JAVA'}); const [message,setMessage]=useState(''); const [results,setResults]=useState<TeacherExamResult[]>([])
  const update=(key:string,value:string)=>setValues((current)=>({...current,[key]:value}))
  const load=()=>void getManagedExams().then((items)=>{setExams(items);if(!examId&&items[0])setExamId(items[0].id)}).catch((e:unknown)=>setMessage(e instanceof Error?e.message:'Không thể tải kỳ thi.'))
  useEffect(load, [])
  const submit=async(event:FormEvent)=>{event.preventDefault();setMessage('');try{if(mode==='create'){const exam=await createExam({slug:values.slug??'',title:values.title??'',description:values.description??'',scheduledAt:new Date(values.scheduledAt??'').toISOString(),durationMinutes:Number(values.duration)});setExamId(exam.id);setMessage(`Đã tạo kỳ thi. ID: ${exam.id}`);load()}else if(mode==='question'){const type=values.type as ExamQuestionType;const options=type==='MULTIPLE_CHOICE'?(values.options??'').split('\n').map(v=>v.trim()).filter(Boolean):[];await addExamQuestion(examId,{type,prompt:values.prompt??'',options,correctOptionIndex:type==='MULTIPLE_CHOICE'?Number(values.correct)-1:undefined,codingLanguage:type==='CODING'?values.language as CodeLanguage:undefined,points:Number(values.points),position:Number(values.position)});setMessage('Đã thêm câu hỏi.')}else{setResults(await getExamResults(examId))}}catch(e){setMessage(e instanceof Error?e.message:'Không thể lưu kỳ thi.')}}
  return <div><div className="flex flex-wrap items-center justify-between gap-3"><button onClick={onBack} className="text-sm text-blue-600">← Giao diện sinh viên</button><div className="flex gap-2">{(['create','question','results'] as const).map(item=><button key={item} onClick={()=>setMode(item)} className={`rounded-full px-3 py-2 text-xs font-bold ${mode===item?'bg-blue-600 text-white':'border border-blue-200 text-slate-600'}`}>{item==='create'?'Tạo kỳ thi':item==='question'?'Thêm câu hỏi':'Kết quả'}</button>)}</div></div>
    <form onSubmit={(e)=>void submit(e)} className="mt-6 rounded-2xl border border-blue-100 bg-white/60 p-5 sm:p-7"><div className="grid gap-4 sm:grid-cols-2">
      {mode!=='create'?<Select label="Kỳ thi" value={examId} onChange={setExamId} options={exams.map(e=>({value:e.id,label:e.title}))}/>:null}
      {mode==='create'?<><Field label="Slug" value={values.slug} onChange={v=>update('slug',v)}/><Field label="Tên kỳ thi" value={values.title} onChange={v=>update('title',v)}/><Field label="Thời gian bắt đầu" type="datetime-local" value={values.scheduledAt} onChange={v=>update('scheduledAt',v)}/><Field label="Thời lượng (phút)" type="number" value={values.duration} onChange={v=>update('duration',v)}/><Area label="Mô tả" value={values.description} onChange={v=>update('description',v)}/></>:null}
      {mode==='question'?<><Select label="Loại câu hỏi" value={values.type} onChange={v=>update('type',v)} options={[{value:'MULTIPLE_CHOICE',label:'Multiple Choice'},{value:'CODING',label:'Coding'}]}/><Field label="Thứ tự" type="number" value={values.position} onChange={v=>update('position',v)}/><Area label="Nội dung câu hỏi" value={values.prompt} onChange={v=>update('prompt',v)}/>{values.type==='MULTIPLE_CHOICE'?<><Area label="Các lựa chọn (mỗi dòng một đáp án)" value={values.options} onChange={v=>update('options',v)}/><Field label="Đáp án đúng (1, 2, ...)" type="number" value={values.correct} onChange={v=>update('correct',v)}/></>:<Select label="Ngôn ngữ" value={values.language} onChange={v=>update('language',v)} options={['CPP','JAVA','PYTHON','HTML','MYSQL'].map(v=>({value:v,label:v}))}/>}<Field label="Điểm" type="number" value={values.points} onChange={v=>update('points',v)}/></>:null}
      <div className="sm:col-span-2"><button className="rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-black text-white">{mode==='results'?'Tải kết quả':'Lưu'}</button></div></div>{message?<p className="mt-4 text-sm text-slate-700">{message}</p>:null}</form>
    {mode==='results'&&results.length>0?<div className="mt-5 overflow-x-auto rounded-xl border border-blue-100"><table className="w-full text-left text-sm"><thead className="bg-white text-xs text-slate-500"><tr><th className="p-3">Student ID</th><th className="p-3">Trạng thái</th><th className="p-3">Điểm tự động</th><th className="p-3">Bài làm</th></tr></thead><tbody>{results.map(r=><tr key={r.attemptId} className="border-t border-blue-100 text-slate-700"><td className="p-3 font-mono text-xs">{r.studentId}</td><td className="p-3">{r.status}</td><td className="p-3">{r.automaticScore}/{r.automaticMaxScore}<span className="block text-xs text-amber-300">{r.pendingCodingQuestions} coding chờ chấm</span></td><td className="p-3"><details><summary className="cursor-pointer text-blue-600">{r.answers.length} câu đã trả lời</summary><div className="mt-2 space-y-2">{r.answers.map(answer=><pre key={answer.id} className="max-w-md overflow-x-auto whitespace-pre-wrap rounded bg-blue-50 p-2 text-xs text-slate-600">{answer.sourceCode ?? `Lựa chọn #${(answer.selectedOptionIndex ?? 0)+1}`}</pre>)}</div></details></td></tr>)}</tbody></table></div>:null}
  </div>
}
function Field({label,value='',onChange,type='text'}:{label:string;value?:string;onChange:(v:string)=>void;type?:string}){return <label className="text-xs text-slate-600">{label}<input required type={type} min={type==='number'?1:undefined} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-lg border border-blue-200 bg-blue-50 px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-blue-500"/></label>}
function Area({label,value='',onChange}:{label:string;value?:string;onChange:(v:string)=>void}){return <label className="text-xs text-slate-600 sm:col-span-2">{label}<textarea required rows={4} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-lg border border-blue-200 bg-blue-50 px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-blue-500"/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <label className="text-xs text-slate-600">{label}<select required value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full rounded-lg border border-blue-200 bg-blue-50 px-3 py-2.5 text-sm text-slate-900">{options.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
